Table "users" {
  "id" int [pk]
  "display_name" varchar
  "email" varchar
  "password" varchar
  "image" varchar
}

Table "posts" {
  "id" int [pk]
  "title" varchar
  "content" varchar
  "user_id" varchar
  "inserted_at" timestamp
  "updated_at" timestamp
}

Ref:"users"."id" < "posts"."user_id"
